# Generated by Django 5.2.6 on 2025-09-16 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='product',
            new_name='products',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('IN PROCESS', 'In process'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='IN PROCESS'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
